apiVersion: v1
kind: PersistentVolume
metadata:
  name: kanbunny-data-optiplex2
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: kanbunny-hostpath
  hostPath:
    path: /home/ross/k3s-data/kanbunny
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - optiplex2
